# Generated by Django 4.1.7 on 2023-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addworker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
